
Date: 2022-07-24 22:21:14.531206

[send_post]---->Traceback (most recent call last):
  File "c:\code\bot_swiss\bot.py", line 129, in send_post
    bot.forward_message(281321076, CHANNEL_ID, message_id)
  File "C:\Users\mdpru\AppData\Local\Programs\Python\Python38\lib\site-packages\telebot\__init__.py", line 613, in forward_message
    apihelper.forward_message(self.token, chat_id, from_chat_id, message_id, disable_notification))
  File "C:\Users\mdpru\AppData\Local\Programs\Python\Python38\lib\site-packages\telebot\apihelper.py", line 254, in forward_message
    return _make_request(token, method_url, params=payload)
  File "C:\Users\mdpru\AppData\Local\Programs\Python\Python38\lib\site-packages\telebot\apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "C:\Users\mdpru\AppData\Local\Programs\Python\Python38\lib\site-packages\telebot\apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
[b'{"ok":false,"error_code":400,"description":"Bad Request: chat not found"}']
